services:
  db:
    image: postgres:16
    container_name: kolayis_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kolayis
      POSTGRES_PASSWORD: kolayis123
      POSTGRES_DB: kolayis_db
    ports:
      - "5432:5432"
    volumes:
      - kolayis_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: kolayis_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kolayis.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  kolayis_pgdata:
